### PR TITLE
improve src-101 standard

### PR DESCRIPTION
**Pull request by superboyiii**

### CODE REVIEW

**Comment by btcopenstamp** [comment]
Hi @reinamora137 When discussing the SRC101 protocol specifications with the Bitname team, we encountered some disagreements. To better track the discussion, we will present our questions here, so that everyone can share their opinions and suggestions.

**Comment by btcopenstamp** [comment]
@superboyiii If the `pri` and `wll` fields in the deploy transaction are external links, what impact would it have on the indexer's logic and the consensus among nodes if those external links become invalid or are subsequently changed?

Because this is an open protocol, we cannot guarantee that all the links in the deploy transactions will be permanently accessible and that their content will remain unchanged.

**Comment by superboyiii** [comment]
> @superboyiii If the `pri` and `wll` fields in the deploy transaction are external links, what impact would it have on the indexer's logic and the consensus among nodes if those external links become invalid or are subsequently changed?
> 
> Because this is an open protocol, we cannot guarantee that all the links in the deploy transactions will be permanently accessible and that their content will remain unchanged.

Thanks for your good advice. Yes, that's the risk. Now we've added a similar signature mechinisam as SRC-721 did. Could you review it again?

**Comment by btcopenstamp** [comment]
@superboyiii Just checked. It looks much better now. Appreciate your work. 

To keep the protocol more general, I would suggest adding "token_ids", "deploy_hash", and "dua" to the sig generation in the mint json. Like,

{"coef": "500","address": "bc1q7epcly9u55yut5k7ykmlcyrp87knt8gxd7knnt","tokenid": ["c3VwZXJib3k=","ZGF5ZHJlYW0=","Yml0aGVybw=="],"hash":"38091b803f794e50dcc10a9091becaf4f65d35d3ef9e71cfa90c7936af50757e","dua":"1"}. 

It can help the domain service provider to control the sig only working for some specific conditional domains. 

And you should also add "conef" in the mint json data, otherwise you're unable to verify the sig.

**Comment by btcopenstamp** [comment]
Since encoding the data into multi-sig outputs needs significant transaction fee costs, I strongly recommend using OLGA to encode the JSON data. This method will reduce transaction costs by at least 75%, significantly saving users' transaction fees and making the experience much more user-friendly..

It's also a much easier encoding method than Multi-Sig outputs. Here is doc to refer. https://docs.openstamp.io/introduction/olga-octet-linked-graphics-and-artifacts

And current stampchain indexer supports OLGA encoding for image stamps and will support OLGA for SRC20 in the future.

**Comment by superboyiii** [comment]
> @superboyiii Just checked. It looks much better now. Appreciate your work.
> 
> To keep the protocol more general, I would suggest adding "token_ids", "deploy_hash", and "dua" to the sig generation in the mint json. Like,
> 
> {"coef": "500","address": "bc1q7epcly9u55yut5k7ykmlcyrp87knt8gxd7knnt","tokenid": ["c3VwZXJib3k=","ZGF5ZHJlYW0=","Yml0aGVybw=="],"hash":"38091b803f794e50dcc10a9091becaf4f65d35d3ef9e71cfa90c7936af50757e","dua":"1"}.
> 
> It can help the domain service provider to control the sig only working for some specific conditional domains.
> 
> And you should also add "conef" in the mint json data, otherwise you're unable to verify the sig.

Good idea. Just implemented. `hash` seems is not suitable to be there since all these are working around the only one deploy txid. `sig` can't cross diffrent deploy txid.

**Comment by btcopenstamp** [comment]
> > @superboyiii Just checked. It looks much better now. Appreciate your work.
> > To keep the protocol more general, I would suggest adding "token_ids", "deploy_hash", and "dua" to the sig generation in the mint json. Like,
> > {"coef": "500","address": "bc1q7epcly9u55yut5k7ykmlcyrp87knt8gxd7knnt","tokenid": ["c3VwZXJib3k=","ZGF5ZHJlYW0=","Yml0aGVybw=="],"hash":"38091b803f794e50dcc10a9091becaf4f65d35d3ef9e71cfa90c7936af50757e","dua":"1"}.
> > It can help the domain service provider to control the sig only working for some specific conditional domains.
> > And you should also add "conef" in the mint json data, otherwise you're unable to verify the sig.
> 
> Good idea. Just implemented. `hash` seems is not suitable to be there since all these are working around the only one deploy txid. `sig` can't cross diffrent deploy txid.

If the deployment hash isn't used to generate the signature, then one signature could be suitable for different deployment hashes as long as they have the same owner (private key).

**Comment by superboyiii** [comment]
> > > @superboyiii Just checked. It looks much better now. Appreciate your work.
> > > To keep the protocol more general, I would suggest adding "token_ids", "deploy_hash", and "dua" to the sig generation in the mint json. Like,
> > > {"coef": "500","address": "bc1q7epcly9u55yut5k7ykmlcyrp87knt8gxd7knnt","tokenid": ["c3VwZXJib3k=","ZGF5ZHJlYW0=","Yml0aGVybw=="],"hash":"38091b803f794e50dcc10a9091becaf4f65d35d3ef9e71cfa90c7936af50757e","dua":"1"}.
> > > It can help the domain service provider to control the sig only working for some specific conditional domains.
> > > And you should also add "conef" in the mint json data, otherwise you're unable to verify the sig.
> > 
> > 
> > Good idea. Just implemented. `hash` seems is not suitable to be there since all these are working around the only one deploy txid. `sig` can't cross diffrent deploy txid.
> 
> If the deployment hash isn't used to generate the signature, then one signature could be suitable for different deployment hashes as long as they have the same owner (private key).

Got it. Done.

**Pull request merged**
